# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Frontend RheinMain
email: info@frontend-rheinmain.de
description: Community-Hub für Frontend-Entwickler in RheinMain

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
avatar: https://cloud.githubusercontent.com/assets/8395991/3862062/81fb56d2-1f36-11e4-9fbb-d0af073157fa.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@frontend-rheinmain.de
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: yes
  twitter: frontend_rm
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

paginate: 5
paginate_path: "/page:num"

sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
